on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_version: ${{ env.TAG_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - run: |
          echo "Merge commit: ${{ github.event.pull_request.merge_commit_sha }}. Base branch: ${{ github.base_ref}} Merged branch: ${{ github.head_ref}}"
      - run: | 
          echo "${{ github.head_ref }}" | sed 's/release\//TAG_VERSION=/'>> "$GITHUB_ENV"
      - run: |
          echo "Tag version: [$TAG_VERSION]"

      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions Tag Bot"
          git config user.email "github-actions-tag-bot@github.com"
          git tag -a ${{ env.TAG_VERSION }} -m "Release ${{ env.TAG_VERSION }}"
          git push origin ${{ env.TAG_VERSION }}

      - name: Fetch and display the last three tags
        run: |
          git fetch --tags
          echo "The last three tags are:"
          git tag --sort=-creatordate | head -n 3

      - name: Print tag version
        run: echo ${{ env.TAG_VERSION }}
  
  generate-changelog:
    name: Generate changelog
    needs: tag-release
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -v --latest --no-exec --tag ${{ steps.tag-release.outputs.tag_version }} --github-repo ${{ github.repository }}
        env:
          OUTPUT: CHANGES.md

  publish-binaries:
    name: Publish binaries
    needs: 
      - tag-release
      - generate-changelog
    env:
      release_version: ${{ needs.tag-release.outputs.tag_version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hatchling
        run: pip install --upgrade hatchling build
      - name: Packaging
        run: |
          echo "Packaging version ${{ env.release_version }}"
          python -m build
      - name: Publish to GitHub (pre-release)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ env.release_version}}
          release_name: "Release: ${{ env.release_version}}"
          prerelease: ${{ contains(env.release_version, '-') || contains(env.release_version, '+') }}
          promote: false
          draft: false
          body: ${{ needs.generate-changelog.outputs.release_body }}
