on:
  push:
    branches:
      - 'main'

jobs:
  if_merged:
    # if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The PR was merged. Event ${{ toJSON(github.event) }} was merged"
      - run: |
          echo "Env ${{ toJSON(env) }}"

