on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_n_release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - run: |
          echo "Merge commit: ${{ github.event.pull_request.merge_commit_sha }}. Base branch: ${{ github.base_ref}} Merged branch: ${{ github.head_ref}}"
      - run: | 
          echo "${{ github.head_ref }}" | sed 's/release\//TAG_VERSION=/'>> "$GITHUB_ENV"
      - run: |
          echo "Tag version: [$TAG_VERSION]"

      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions Tag Bot"
          git config user.email "github-actions-tag-bot@github.com"
          git tag -a ${{ env.TAG_VERSION }} -m "Release ${{ env.TAG_VERSION }}"
          git push origin ${{ env.TAG_VERSION }}

      - name: Fetch and display the last three tags
        run: |
          git fetch --tags
          echo "The last three tags are:"
          git tag --sort=-creatordate | head -n 3

